### PR TITLE
wrap img tags in a tags

### PR DESCRIPTION
**Pull request by mobby12345**
this should let you "click" on an image using cVim

### CODE REVIEW

**Comment by KeyboardFire** [comment]
+1, `` is dubious at best (I've never even heard of it until seeing it in the Miaou source) and bad for accessibility, as well as not being compatible with extensions such as Pentadactyl for Firefox or cVim for Chromium.

**Comment by KeyboardFire** [comment]
... taking a closer look, `href` isn't even valid on `img`, and the clicking is handled with JavaScript. No point in relying on intercepting `click` with JS when you can simply wrap with `<a>`, which is far more semantically accurate.

**Comment by Canop** [comment]
Reminder: 
* it's best to discuss on Miaou before writing a PR
* there's a test suite (run ./test.sh, I'll work on making travis aware of it), it must be updated when you change code making it fail

**Comment by Canop** [comment]
Right now, this has many unwanted side effects:

* broken room description on home page
* clicking the image in the room description open the image instead of the room
* clicking the image in the chat unexpectedly open in the same tab (remember, this is a chat application, not a web site)
* clicking the image in notable messages or search results open the image instead of going to the message

That's why I removed the `a` tag initially. I'm not sure of what would be the best solution for cvim compatibility (and other accessibility problems related to not having a `a` element).

**Comment by mobby12345** [comment]
Hmm... I could add `target="_blank"` to make it open in a new tab. I'm not sure what to do for the other problems though...

**Comment by Canop** [comment]
Obviously we need the JS handling part. I don't know if cvim is OK with an image in an href element whose behavior is changed by an event handler. In that case it might be possible to combine both.

**Pull request closed without merging**
